- fireq/web.py
First time, access to / redirects to /login, but second time doesn't.
> Fix auth bug

- docs/ci.md
- fireq/cli.py
- tpl/superdesk-client/check-docs.sh
- tpl/superdesk-server/check-docs.sh
- tpl/superdesk-server/deploy.sh
Docs for [superdesk-client-core](https://github.com/superdesk/superdesk-client-core/) are not working properly now.
So enable docs only for [superdesk-core](https://github.com/superdesk/superdesk-core) in CI.
Ref: #9
> Generate docs for cores

- fireq/__init__.py
- fireq/cli.py
- tpl/ci-nginx.sh
Usage `./fire ci-nginx` with settings like this:
```
"proxy_ssh": {
"2200": "sd-master",
"2201": "sd-naspeh"
}
```
Link `<domain>/ssh` shows `ssh` command with proper port.
@scanterog you can check this: https://sd-thesource.test.superdesk.org/ssh
> Adding ssh proxy using "config.proxy_ssh"

- fireq/cli.py
- tpl/lxc-init.sh
- tpl/superdesk-fidelity/build-src-repo.sh
Aside from that, lxc-init bind mount root/.ssh folder into base container for priv repo access. BTW, I've generated new base-sd--13 with these changes.
> Add files overwrite with stash repo for Fidelity

- tpl/add-chrome.sh
e2e tests are working with latest google chrome (60.0.3112.78-1) but it's not working with latest chromium (59.0.3071.109) available in ubuntu 16 repo. It was working before because it was using chromium 58.0.3029.110. In new chromium it fails to create session: `From: Task: WebDriver.createSession()`
Aside from that, in order to make npmtest work, it also needs changes in karma.conf: https://github.com/superdesk/superdesk-client-core/pull/1749. I've tested it and it's working. You can check results here: https://test.superdesk.org/logs/3/dev2/latest/sdc-fixtest/. Alternatively, we might look another way to provide the `--no-sandbox` as default custom param to chrome (it doesn't provide a file as chromium does).
> Replace chromium by chrome for e2e tests

- tpl/newsroom/deploy.sh
- tpl/newsroom/nginx.conf
it's used for media, serve static via /static
> fix assets url

- tpl/superdesk-analytics/build-src.sh
it was removing trailing `,` from package.json which broke npm install
> fix superdesk-analytics build

- tpl/superdesk-client/build.sh
- tpl/superdesk/deploy.sh
Fixes webpack build crashing due to getting out of memory:
```
Running "webpack:build" (webpack) task
92% chunk asset optimization                                                             
<--- Last few GCs --->
[21719:0x2655d30]   194174 ms: Mark-sweep 1384.7 (1497.6) -> 1384.6 (1499.6) MB, 1306.0 / 0.0 ms  allocation failure GC in old space requested
[21719:0x2655d30]   195322 ms: Mark-sweep 1384.6 (1499.6) -> 1384.5 (1460.6) MB, 1147.4 / 0.0 ms  last resort GC in old space requested
[21719:0x2655d30]   196633 ms: Mark-sweep 1384.5 (1460.6) -> 1384.5 (1455.6) MB, 1309.6 / 0.0 ms  last resort GC in old space requested
<--- JS stacktrace --->
==== JS stack trace =========================================
Security context: 0x152283425879 <JSObject>
1: /* anonymous */ …
```
> fix node memory setting

- tpl/superdesk/activate.sh
Since the internal request is HTTP and not HTTPS, we must use  
`AUTHLIB_INSECURE_TRANSPORT=1`
to avoid an error raised by authlib.
> Set AUTHLIB_INSECURE_TRANSPORT to true.

- fireq/gh.py
👋 from GitHub.
The `/installations/:installation_id/access_tokens` GitHub API endpoint is no longer documented and will soon be deprecated. As the Fireq App uses this endpoint extensively (~40,000 calls per day), we hope you'll accept this PR to keep your App working as intended.
This branch updates the endpoint to the preferred and supported version: [`app/installations/:installation_id/access_tokens`](https://developer.github.com/apps/building-github-apps/authenticating-with-github-apps/#authenticating-as-an-installation). The response from the new endpoint is the same as the old endpoint, so there should be no other functional changes necessary.
> Use new version of GitHub App installation access token endpoint

- tpl/superdesk/build.sh
This is because `build-sams` requires the `.fireq.json` file from `superdesk-core` after installing it
> Build SAMS after installing superdesk-core

- tpl/add-smtp.py
Ubuntu 16.04 has updated its latest stable Python 3.6 and that now has changed how its `smtpd` behaves. It now defaults the `decode_data` to `False` and requires you to provide a dictionary for in `process_message` to process more `mail_options`.
Ergo, this commit!
Ref: https://python.readthedocs.io/en/stable/whatsnew/3.5.html#smtpd
> SMTPServer and process_message sig update for 3.6

- tpl/superdesk/prepopulate.sh
The `qa-02-00` branch was failing to build with  Superdesk-Core >= 2.0.5 because schema:migrate was not being executed
> run schema:migrate when test_data=0

- tpl/liveblog/build.sh
Liveblog test instances deployments are failing and I think it's because `pip` has changed the way it resolves dependency conflicts. Given that we haven't upgraded Liveblog to use a newer version of `superdesk` and other dependencies, we need to stick to these versions for now.
> Lock setuptools and pip versions for Liveblog

- tpl/superdesk-belga/Procfile
- tpl/superdesk-tlp/Procfile
- tpl/superdesk/Procfile
there is no `--pid` option and there never was,
new celery will raise error on unknown param.
> update Procfile to work with new celery

- tpl/superdesk-client/build.sh
I have changed test server directory from `test-server` to `e2e/server` and fireq is failing on that [PR](https://github.com/superdesk/superdesk-client-core/pull/3983) with the following message:
```
-bash: line 262: cd: /opt/superdesk/client-core/test-server: No such file or directory
```
I also need to change the build, so it runs `npm run build` and allows the client to handle the details. I have added a branch for new behavior, and kept the `else` for old so it works for existing releases.
> update test server dir

- tpl/superdesk/build-init.sh
This reverts commit 90255cfd968aadc3ed44fb86ef5a8732838249a7.
Pip has now fixed this issue. This version restriction is causing issues with NewsHub build (https://github.com/superdesk/newsroom-app-stt/pull/1)
> Revert "fix(install): Use pip v21.2"

- tpl/superdesk/activate.sh
When the `sams` option is enabled in `.fireq.json`, SAMS is installed and set up.
In customer repos this may not be desired, so we set the SAMS env. vars regardless if they're used or not
> Set SAMS env vars regardless if its used

- fireq/cli.py
Currently, liveblog instances are being put on `data-sd` db host which is causing issues. Since it doesn't work on modern ES ;) and hence it requires old-school version **`1.7.6`** to be working 😜
> Use its own db-host for liveblog

- fireq/web.py
Instances on our infrastructure are created for PRs by dependabot. These instances aren't used by our team to verify features etc.
Skip building instances for PRs created by a `Bot` user type.
**Note:** If needing to verify building instances from dependabot PRs, we should use Github actions instead
Docs: https://docs.github.com/en/webhooks/webhook-events-and-payloads?actionType=opened#pull_request
Partial example webhook body:
```json
{
"pull_request": {
"url": "https://api.github.com/repos/superdesk/superdesk/pulls/3734",
"title": "Bump superdesk-core from `17efc4f` to `6ac2650` in /client",
"user": {
"login": "dependabot[bot]",
"id": 49699333,            
"type": "Bot"
}
}
}
```
> [SDESK-7672] Skip building instances for PRs by bots

- README.md
- tpl/superdesk/build.sh
- tpl/superdesk/install-highcharts-server.sh
Add support for conditional installation of the Highcharts export server if `analytics` is enabled in `fireq.json`. The highcharts export server is required for the analytics scheduled email reports to work properly. 
- Added a new script `install-highcharts-server.sh` that checks if analytics is enabled via the analytics flag in `.fireq.json` and only proceeds with installation if analytics is set to "true"
- Modified `build.sh` to include the highcharts export server installation step
This PR depends on https://github.com/superdesk/superdesk-analytics/pull/183 so the `install-highcharts-server` command is available.
Related to [SDESK-7591]
[SDESK-7591]: https://sofab.atlassian.net/browse/SDESK-7591?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1ci …
> [SDESK-7591] Install highcharts server if analytics is enabled
