tpl/init/lb-syndtest1.sh, tpl/init/lb-syndtest2.sh, tpl/init/lb-syndtest3.sh
Enable syndication for those 3 instances:
* http://lb-syndtest1.test.superdesk.org/
* http://lb-syndtest2.test.superdesk.org/
* http://lb-syndtest3.test.superdesk.org/
=> Created specific configuration for syndication tests instances

README.md, docs/lxc.md, files/liveblog/README.md, files/superdesk-dev/README.md, files/superdesk-dev/deploy, files/superdesk-dev/install, files/superdesk/README.md, fireq/cli.py, tpl/superdesk-dev/README.md, tpl/superdesk/README.md, tpl/superdesk/supervisor.conf
It is better to look into these links:
- https://github.com/superdesk/fireq/tree/docs/files/superdesk-dev it should be pretty usable :)
- https://github.com/superdesk/fireq/tree/docs/files/superdesk needs more clarifications yet
I'm going to share `superdesk-dev` first in `#superdesk` channel.
Cc: @petrjasek, @hlmnrmr, @jerome-poisson
=> Update instructions to install Superdesk/Liveblog

fireq/cli.py, tpl/add-chrome.sh, tpl/add-elastic.sh, tpl/add-mongo.sh, tpl/add-nginx.sh, tpl/add-supervisor.sh, tpl/lxc-base.sh, tpl/lxc-init.sh
- fixes `npm test` for client core (with new chromium and --no-sandbox)
- some cleanup
=> New "lxc-base" subcommand

files/superdesk/install
it's a requirement for saml auth library
=> Install libxmlsec1 dependency

fireq/cli.py
it's running them all already, but twice
=> run all e2e tests at once

fireq/cli.py, tpl/superdesk/activate.sh, tpl/superdesk/build-init.sh, tpl/superdesk/config.sh
and set different elastic port for 7
=> read elastic version config from superdesk core

tpl/newsroom/deploy.sh
=> escape $ in newsroom Procfile

fireq/cli.py, tpl/superdesk/activate.sh
eg:
```
"env": {
"sd": {
"FOO": "bar",
"BAZ": "bar"
}
}
```
=> allow adding env vars for scope via config.json

fireq/cli.py
related to https://github.com/superdesk/superdesk-belga/pull/235
=> ES7 for belga

tpl/superdesk/build-grammalecte.sh, tpl/superdesk/build.sh, tpl/superdesk/deploy.sh, tpl/superdesk/service-grammalecte.sh
How to enable grammalecte per instance https://github.com/superdesk/superdesk-belga/pull/247/files
=> Run grammalecte spellchecker server if enabled

fireq/cli.py
=> disable archived projects

tpl/ci-www.sh
it will always destroy the old lxc container
so the instance won't keep working with old code
SDESK-5567
=> make www fail on error

tpl/ci-www.sh
=> Revert "make www fail on error"

tpl/add-node.sh, tpl/liveblog/build.sh, tpl/newshub-cp/build.sh, tpl/newsroom/build.sh, tpl/superdesk-client/build.sh, tpl/superdesk-client/check-e2e.sh, tpl/superdesk-server/build.sh, tpl/superdesk/build.sh
it's consuming resource and is not useful on CI
also try to use npm ci if possible
=> avoid running audit when installing npm packages

tpl/superdesk-planning/build-src.sh
This feature is ready in the Planning branch: https://github.com/superdesk/superdesk-planning/tree/support/1.33
=> Planning: Support superdesk_branch json config

tpl/superdesk/build-init.sh
CP instance started failing, https://github.com/superdesk/superdesk-cp/pull/128
=> Install libexempi3 on build

tpl/add-smtp.sh
when using localhost it was only working when connecting to localhost, not 127.0.0.1
=> make smtp server work on both localhost and 127.0.0.1

docs/ci.md, docs/lxc.md, fireq/__init__.py, fireq/cli.py, fireq/web.py, tpl/ci-build.sh, tpl/ci-check.sh, tpl/ci-deploy.sh, tpl/ci-nginx.sh, tpl/ci-www.sh, tpl/lxc-base.sh, tpl/lxc-db.sh, tpl/lxc-expose.sh, tpl/lxc-init.sh, tpl/lxc-rm.sh, tpl/lxc-wait.sh, tpl/newshub-cp/deploy.sh, tpl/newsroom-app/deploy.sh, tpl/newsroom/deploy.sh, tpl/superdesk-new/deploy.sh, tpl/superdesk/deploy.sh
Brings support for:
* lxd 5.x stable api
* python 3.8
* compatibility with latest asyncio and aiohttp* modules
* removes cpu limits
Already tested on the internal _fireq-beta_!
=> Latest stable lxd port and newer python support

fireq/cli.py, tpl/superdesk/build-init.sh, tpl/superdesk/build-src-repo.sh
- configure git to use authentication for github.com
- init submodules when building repo
=> add support for private submodules

tpl/newshub-cp/deploy.sh, tpl/newsroom-app/deploy.sh, tpl/newsroom/deploy.sh, tpl/superdesk-belga/Procfile, tpl/superdesk-new/deploy.sh, tpl/superdesk-tlp/Procfile, tpl/superdesk/Procfile, tpl/superdesk/deploy.sh
=> fix empty logs
